version: '3.9'

services:
  backend:
    image: expense-backend
    build: ./backend
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGODB_NAME}?authSource=admin"

  mongo:
    image: mongo:6.0.19
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    ports:
      - "27017:27017"
    volumes: 
      - mongo:/data/db
  
  mongo-express:
    image: mongo-express:latest
    env_file: 
      - ./backend/.env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo: {}
